apiVersion: v1
kind: Service
metadata:
  name: debate-admin-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: debate-admin
